version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - dev

  webserver:
    image: nginx:alpine
    container_name: dev_webserver
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - dev

  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/volumes/mysql-data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev

  redis:
    image: redis:alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/volumes/redis-data:/data
    networks:
      - dev

  mailtrap:
    image: mailhog/mailhog
    container_name: dev_mailtrap
    ports:
      - "8025:8025"
    networks:
      - dev

  postman:
    image: postman/newman
    container_name: dev_postman
    volumes:
      - ./collections:/etc/newman
    entrypoint: ["newman", "run", "/etc/newman/your_collection.json"]
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
